In [3]:
from obspy.clients.fdsn import Client
from obspy.clients.iris import Client as Client_iris
from obspy import UTCDateTime
import numpy as np
from obspy.signal.trigger import classic_sta_lta
from obspy.signal.trigger import plot_trigger
%matplotlib inline

In [4]:
# connect to server
client = Client("http://127.0.0.1:1001")
# get events
event_list=client.get_events()
# get otimes
ori1=event_list[1].origins[0].time
# get_stations
inv=client.get_stations(network="CX",starttime=ori1)
# get one station location
slon=inv[0][0].longitude
slat=inv[0][0].latitude
inc=0
for event in event_list[:5]:
    # get epicenter
    elon = event.origins[0].longitude
    elat = event.origins[0].latitude
    # get OT
    ori=event.origins[0].time
    # calculate distance
    client1 = Client_iris()
    result = client1.distaz(slat, slon, elat, elon)
    print(result['distance'])
    if result['distance'] > 2:
        continue
    # get waveforms
    st1 = client.get_waveforms("CX","*","*","*",ori,ori+60)
    #print(st1)
    
    
   # slice waveform and save picture 
    for tr in st1:
        dt = tr.stats.starttime
        ed = dt
        cc=0
        while True:
            ed = ed + 10
            fname1=".\\data\\P_"+str(inc)+".png"
            fname2=".\\data\\P_"+str(inc)+".txt"
    
            if ed > tr.stats.endtime:
                break
        
            tr.slice(dt+cc*10,ed).plot(outfile=fname1,format="png")
            np.savetxt(fname2, tr.data, delimiter=',')
            cc = cc + 1
            inc = inc + 1

48.30659
5.01578
19.99585
0.72475
2.12489


In [ ]:
tr.data

In [ ]:
np.savetxt('data.txt', tr.data, delimiter=',')

In [5]:
import glob

In [7]:
flist=glob.glob(".\\data\\*.txt")

In [41]:
data1=np.loadtxt(flist[0])
data2=np.loadtxt(flist[1])
data3=np.loadtxt(flist[2])

In [22]:
data1.shape

(6001,)

In [23]:
data2.shape

(6001,)

In [38]:
data=np.vstack((data1,data2))

In [39]:
data.shape

(2, 6001)

In [40]:
data

array([[ -197.,  -190.,  -173., ...,   -34.,  4705.,  9545.],
       [ 3281.,  3302.,  3315., ..., -2706., -4641., -6932.]])

In [42]:
data=np.vstack((data,data3))

In [43]:
data.shape

(3, 6001)

In [44]:
#for feature
flag=0
for i in flist:
    if flag==0:
        data=np.loadtxt(i)
        flag=1
    else:
        data_tmp=np.loadtxt(i)
        data=np.vstack((data,data_tmp))

In [45]:
data.shape

(252, 6001)

In [54]:
np.savetxt('feature.txt', data, delimiter=',')

In [55]:
np.loadtxt('feature.txt',delimiter=',')

array([[ -197.,  -190.,  -173., ...,   -34.,  4705.,  9545.],
       [ 3281.,  3302.,  3315., ..., -2706., -4641., -6932.],
       [-1767., -1784., -1812., ...,   943.,   920.,   912.],
       ..., 
       [ 3281.,  3302.,  3315., ..., -2706., -4641., -6932.],
       [  914.,   914.,   916., ...,   763.,   665.,   836.],
       [  945.,   945.,   943., ...,   437.,   406.,   352.]])

In [47]:
flist

['.\\data\\P_0.txt',
 '.\\data\\P_10.txt',
 '.\\data\\P_100.txt',
 '.\\data\\P_101.txt',
 '.\\data\\P_102.txt',
 '.\\data\\P_103.txt',
 '.\\data\\P_104.txt',
 '.\\data\\P_105.txt',
 '.\\data\\P_106.txt',
 '.\\data\\P_107.txt',
 '.\\data\\P_108.txt',
 '.\\data\\P_109.txt',
 '.\\data\\P_11.txt',
 '.\\data\\P_110.txt',
 '.\\data\\P_111.txt',
 '.\\data\\P_112.txt',
 '.\\data\\P_113.txt',
 '.\\data\\P_114.txt',
 '.\\data\\P_115.txt',
 '.\\data\\P_116.txt',
 '.\\data\\P_117.txt',
 '.\\data\\P_118.txt',
 '.\\data\\P_119.txt',
 '.\\data\\P_12.txt',
 '.\\data\\P_120.txt',
 '.\\data\\P_121.txt',
 '.\\data\\P_122.txt',
 '.\\data\\P_123.txt',
 '.\\data\\P_124.txt',
 '.\\data\\P_125.txt',
 '.\\data\\P_126.txt',
 '.\\data\\P_127.txt',
 '.\\data\\P_129.txt',
 '.\\data\\P_130.txt',
 '.\\data\\P_131.txt',
 '.\\data\\P_132.txt',
 '.\\data\\P_133.txt',
 '.\\data\\P_135.txt',
 '.\\data\\P_136.txt',
 '.\\data\\P_137.txt',
 '.\\data\\P_138.txt',
 '.\\data\\P_139.txt',
 '.\\data\\P_141.txt',
 '.\\data\\P_142

In [52]:
# For label
label=[]
for i in flist:
    tmp=i.split("_")[0][-1]
    print(i.split("_")[0][-1])
    if tmp=="P":
        label.append(0)
    else:
        label.append(1)

P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
P
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T
T


In [53]:
label

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [56]:
np.savetxt('label.txt', label, delimiter=',')

In [60]:
np.loadtxt('label.txt',delimiter=",")

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0